name: CI
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Download ngrok
        run: wget https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-windows-amd64.zip

      - name: Unzip ngrok
        run: powershell -Command "Expand-Archive -Path ngrok-stable-windows-amd64.zip -DestinationPath ."

      - name: Connect to ngrok
        run: ./ngrok.exe authtoken YOUR_AUTHTOKEN && ./ngrok.exe tcp 3389
