name: CI
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Download ngrok
        run: |
          curl -o ngrok.zip https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-windows-amd64.zip

      - name: Unzip ngrok
        run: |
          powershell -Command "Expand-Archive -Path ngrok.zip -DestinationPath ."

      - name: Connect to ngrok
        run: |
          ./ngrok.exe authtoken ${{ secrets.NGROK_AUTHTOKEN }}
          ./ngrok.exe tcp 3389
